spring:
  application:
    name: ms-email-notification
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: product-created-events
      properties:
        spring:
          json:
            trusted:
              packages: "*"

services:
  product:
    kafka:
      topic:
        name: product-created-events-topic

server:
  port: 0
